
import { AeroBaseConfiguration, INSTANCE } from "@aerobase/core";

/**
 * Initialize all platform SDK's by using configuration generated by AeroBase command line client
 *
 * @param config object containing SDK. Object can be read from file or pasted directly in source code.
 */
export const init = (config: AeroBaseConfiguration): void => {
  return INSTANCE.init(config);
};
